# -*- coding: utf-8 -*-
"""cross attention modification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKy8_gTRIP1FSwuXweW1uxzIn6kltx7z

Modification on June 18
1.  Adding multihead
2.  cross attention using cls token
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

import loralib as lora
from guided_diffusion.guided_diffusion.unet import AttentionBlock
import matplotlib.pyplot as plt

import ipdb

# for 64by64 diffusion that all blocks include emb_layer
layers_include_emb_64 = [
    "input_blocks.1.0",
    "input_blocks.2.0",
    "input_blocks.3.0",
    "input_blocks.4.0",
    "input_blocks.5.0",
    "input_blocks.6.0",
    "input_blocks.7.0",
    "input_blocks.8.0",
    "input_blocks.9.0",
    "input_blocks.10.0",
    "input_blocks.11.0",
    "input_blocks.12.0",
    "input_blocks.13.0",
    "input_blocks.14.0",
    "input_blocks.15.0",
    "middle_block.0",
    "middle_block.2",
    "output_blocks.0.0",
    "output_blocks.1.0",
    "output_blocks.2.0",
    "output_blocks.3.0",
    "output_blocks.3.2",
    "output_blocks.4.0",
    "output_blocks.5.0",
    "output_blocks.6.0",
    "output_blocks.7.0",
    "output_blocks.7.2",
    "output_blocks.8.0",
    "output_blocks.9.0",
    "output_blocks.10.0",
    "output_blocks.11.0",
    "output_blocks.11.2",
    "output_blocks.12.0",
    "output_blocks.13.0",
    "output_blocks.14.0",
    "output_blocks.15.0"
]
# for 128by128 diffusion that all blocks include emb_layer
layers_include_emb_128 = [
    "input_blocks.1.0",
    "input_blocks.2.0",
    "input_blocks.3.0",
    "input_blocks.4.0",
    "input_blocks.5.0",
    "input_blocks.6.0",
    "input_blocks.7.0",
    "input_blocks.8.0",
    "input_blocks.9.0",
    "input_blocks.10.0",
    "input_blocks.11.0",
    "input_blocks.12.0",
    "input_blocks.13.0",
    "input_blocks.14.0",
    "middle_block.0",
    "middle_block.2",
    "output_blocks.0.0",
    "output_blocks.1.0",
    "output_blocks.2.0",
    "output_blocks.2.2",
    "output_blocks.3.0",
    "output_blocks.4.0",
    "output_blocks.5.0",
    "output_blocks.5.2",
    "output_blocks.6.0",
    "output_blocks.7.0",
    "output_blocks.8.0",
    "output_blocks.8.2",
    "output_blocks.9.0",
    "output_blocks.10.0",
    "output_blocks.11.0",
    "output_blocks.11.1",
    "output_blocks.12.0",
    "output_blocks.13.0",
    "output_blocks.14.0"
]


def plot_layer_ratios(
    data, 
    layer_column="Layer Name", 
    ratio_column="Ratio", 
    title="Ranking of Layers by Ratio of LoRA to Original Norm"
):
    """
    Plots a horizontal bar chart for the ratio of LoRA norm to original norm by layer.

    Parameters:
    - data (DataFrame): Pandas DataFrame containing the layer names and ratio values.
    - layer_column (str): The name of the column containing layer names. Default is "Layer Name".
    - ratio_column (str): The name of the column containing ratio values. Default is "Ratio".
    - title (str): Title for the plot. Default is "Ranking of Layers by Ratio of LoRA to Original Norm".

    Example Usage:
    plot_layer_ratios(df, layer_column="Layer Name", ratio_column="Ratio")
    """
    # Sort the DataFrame by the specified ratio column
    sorted_data = data.sort_values(by=ratio_column, ascending=False)

    # Create the plot
    plt.figure(figsize=(10, 6))

    # Define a professional color palette (e.g., shades of blue)
    colors = plt.cm.Blues(sorted_data[ratio_column] / sorted_data[ratio_column].max())

    # Plot horizontal bars
    plt.barh(sorted_data[layer_column], sorted_data[ratio_column], color=colors, alpha=0.9)

    # Add labels and title with a professional style
    plt.xlabel("Ratio", fontsize=12)
    plt.ylabel("Layer Name", fontsize=12)
    plt.title(title, fontsize=14, weight="bold")

    # Invert y-axis for ranking order from top to bottom
    plt.gca().invert_yaxis()

    # Add grid lines for better readability
    plt.grid(axis="x", linestyle="--", alpha=0.6)

    # Add ratio values next to each bar
    for index, value in enumerate(sorted_data[ratio_column]):
        plt.text(value + 0.01, index, f"{value:.4f}", va="center", fontsize=10)

    # Adjust layout for readability
    plt.tight_layout()
    plt.show()



def apply_lora_to_attention_block(attention_block, r=16, lora_alpha=32):
     # Clear any existing hooks to avoid unwanted behavior
    if hasattr(attention_block.qkv, '_forward_hooks'):
            attention_block.qkv._forward_hooks.clear()
    # Replace qkv Conv1d with a LoRA-enhanced Conv1d
    if hasattr(attention_block, 'qkv') and isinstance(attention_block.qkv, nn.Conv1d):     
            attention_block.qkv= lora.Conv1d(
            in_channels=attention_block.qkv.in_channels,
            out_channels=attention_block.qkv.out_channels,
            kernel_size=attention_block.qkv.kernel_size[0],  # Assuming a 1D kernel
            r=r,
            lora_alpha=lora_alpha,
            stride=attention_block.qkv.stride,
            padding=attention_block.qkv.padding,
            bias=attention_block.qkv.bias is not None
        )
    if hasattr(attention_block.proj_out, '_forward_hooks'):
            attention_block.proj_out._forward_hooks.clear()
    # Replace proj_out Conv1d with a LoRA-enhanced Conv1d
    if hasattr(attention_block, 'proj_out') and isinstance(attention_block.proj_out, nn.Conv1d):
            attention_block.proj_out = lora.Conv1d(
            in_channels=attention_block.proj_out.in_channels,
            out_channels=attention_block.proj_out.out_channels,
            kernel_size=attention_block.proj_out.kernel_size[0],  # Assuming a 1D kernel
            r=r,
            lora_alpha=lora_alpha,
            stride=attention_block.proj_out.stride,
            padding=attention_block.proj_out.padding,
            bias=attention_block.proj_out.bias is not None
        )

    return attention_block

def apply_lora_to_unet_model(model, r=16, lora_alpha=32):
    #pdb.set_trace()
    # Traverse through the model to find and replace AttentionBlocks
    for name, module in model.named_modules():
         
        #if isinstance(module, AttentionBlock) and "output_blocks" in name:
            # Apply LoRA to the AttentionBlock and retrieve the modified block
        if isinstance(module, AttentionBlock):
            modified_block = apply_lora_to_attention_block(module, r=r, lora_alpha=lora_alpha)
            # Get the parent module to replace the original block
            parent_name, child_name = name.rsplit('.', 1)
            parent_module = model
            if parent_name:  # If the module is nested
                for attr in parent_name.split('.'):
                    parent_module = getattr(parent_module, attr)
            
            # Replace the original AttentionBlock with the modified one
            setattr(parent_module, child_name, modified_block)

    return model

def print_all_lora_conv1d_layers(model):
    for name, module in model.named_modules():
        if isinstance(module, lora.Conv1d):
            print(f"Layer name: {name}")
            print(module)
            print()  # Print an empty line for readability



def calculate_lora_adjustment(layer):
    # Compute the effective LoRA adjustment: scaling * (lora_A @ lora_B)
    if hasattr(layer, 'lora_A') and hasattr(layer, 'lora_B'):
        return layer.scaling * (layer.lora_B @ layer.lora_A).view(layer.conv.weight.shape) 
    return None



def rank_lora_adjustment(model):
    adjustment_list = []
    
    for name, module in model.named_modules():
        if isinstance(module, AttentionBlock):
            # Calculate LoRA adjustment for `qkv`
            if hasattr(module, 'qkv') and isinstance(module.qkv, lora.Conv1d):
                qkv_adjustment = calculate_lora_adjustment(module.qkv)
                if qkv_adjustment is not None:
                    # Calculate norms and magnitude ratio
                    #ipdb.set_trace()
                    qkv_norm = torch.norm(qkv_adjustment).item()
                    original_qkv_norm = torch.norm(module.qkv.conv.weight).item()
                    qkv_ratio = qkv_norm / original_qkv_norm if original_qkv_norm != 0 else 0

                    # Calculate cosine similarity
                    qkv_cosine_similarity = F.cosine_similarity(
                        module.qkv.conv.weight.view(-1), 
                        qkv_adjustment.view(-1), 
                        dim=0
                    ).item()
                    qkv_direction = "strengthening" if qkv_cosine_similarity > 0 else "negating"

                    # Calculate strength as magnitude ratio multiplied by absolute cosine similarity
                    qkv_strength = qkv_ratio * abs(qkv_cosine_similarity)

                    # Append results
                    adjustment_list.append((
                        f"{name}.qkv", qkv_norm, original_qkv_norm, qkv_ratio, qkv_cosine_similarity, qkv_direction, qkv_strength
                    ))

            # Calculate LoRA adjustment for `proj_out`
            if hasattr(module, 'proj_out') and isinstance(module.proj_out, lora.Conv1d):
                proj_out_adjustment = calculate_lora_adjustment(module.proj_out)
                if proj_out_adjustment is not None:
                    # Calculate norms and magnitude ratio
                    proj_out_norm = torch.norm(proj_out_adjustment).item()
                    original_proj_out_norm = torch.norm(module.proj_out.conv.weight).item()
                    proj_out_ratio = proj_out_norm / original_proj_out_norm if original_proj_out_norm != 0 else 0

                    # Calculate cosine similarity
                    proj_out_cosine_similarity = F.cosine_similarity(
                        module.proj_out.conv.weight.view(-1), 
                        proj_out_adjustment.view(-1), 
                        dim=0
                    ).item()
                    proj_out_direction = "strengthening" if proj_out_cosine_similarity > 0 else "negating"

                    # Calculate strength
                    proj_out_strength = proj_out_ratio * abs(proj_out_cosine_similarity)

                    # Append results
                    adjustment_list.append((
                        f"{name}.proj_out", proj_out_norm, original_proj_out_norm, proj_out_ratio, proj_out_cosine_similarity, proj_out_direction, proj_out_strength
                    ))

    # Sort list by the calculated "strength" in descending order
    adjustment_list.sort(key=lambda x: x[3], reverse=True)

    # Print the sorted list with strength information
    print("Ranking of LoRA adjustments by strength in AttentionBlocks:")
    for layer_name, lora_norm, original_norm, ratio, cosine_similarity, direction, strength in adjustment_list:
        print(f"{layer_name}: LoRA norm = {lora_norm:.4f}, Original norm = {original_norm:.4f}, "
              f"Ratio = {ratio:.4f}, Cosine Similarity = {cosine_similarity:.4f}, Direction = {direction}, "
              f"Strength = {strength:.4f}")
    plot_layer_ratios(adjustment_list)



# Run the function on your model
#rank_attention_blocks_by_lora_adjustment(model)

